# This file was auto-generated by Fern from our API Definition.

import typing

AssetSort = typing.Union[
    typing.Literal[
        "nameAsc",
        "nameDesc",
        "dateAsc",
        "dateDesc",
        "durationAsc",
        "durationDesc",
        "sizeAsc",
        "sizeDesc",
        "kindAsc",
        "kindDesc",
    ],
    typing.Any,
]
