# This file was auto-generated by Fern from our API Definition.

from ...core.unchecked_base_model import UncheckedBaseModel
from .asset_id import AssetId
import typing_extensions
import datetime as dt
from ...core.serialization import FieldMetadata
import pydantic
import typing
from .asset_type import AssetType
from .asset_input_type import AssetInputType
from .asset_visibility import AssetVisibility
from ...core.pydantic_utilities import IS_PYDANTIC_V2


class Asset(UncheckedBaseModel):
    """
    An asset stored in your organization's media library.
    """

    id: AssetId
    created_at: typing_extensions.Annotated[dt.datetime, FieldMetadata(alias="createdAt")] = pydantic.Field()
    """
    The date and time the asset was created.
    """

    updated_at: typing_extensions.Annotated[dt.datetime, FieldMetadata(alias="updatedAt")] = pydantic.Field()
    """
    The date and time the asset was last updated.
    """

    name: typing.Optional[str] = pydantic.Field(default=None)
    """
    The filename of the asset.
    """

    url: typing.Optional[str] = pydantic.Field(default=None)
    """
    The URL to access the asset media.
    """

    size: typing.Optional[int] = pydantic.Field(default=None)
    """
    File size in bytes.
    """

    format: typing.Optional[str] = pydantic.Field(default=None)
    """
    File format/extension (e.g., "mp4", "wav").
    """

    type: AssetType = pydantic.Field()
    """
    The type of asset file.
    """

    input_type: typing_extensions.Annotated[typing.Optional[AssetInputType], FieldMetadata(alias="inputType")] = (
        pydantic.Field(default=None)
    )
    """
    The source type of the asset.
    """

    duration_seconds: typing_extensions.Annotated[typing.Optional[float], FieldMetadata(alias="durationSeconds")] = (
        pydantic.Field(default=None)
    )
    """
    Duration of the media in seconds (for audio/video).
    """

    thumbnail_url: typing_extensions.Annotated[typing.Optional[str], FieldMetadata(alias="thumbnailUrl")] = (
        pydantic.Field(default=None)
    )
    """
    URL to the asset's thumbnail image.
    """

    visibility: AssetVisibility = pydantic.Field()
    """
    Visibility scope for the asset.
    """

    width: typing.Optional[int] = pydantic.Field(default=None)
    """
    Width in pixels (for video/image).
    """

    height: typing.Optional[int] = pydantic.Field(default=None)
    """
    Height in pixels (for video/image).
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
