# This file was auto-generated by Fern from our API Definition.

import typing

AssetInputType = typing.Union[
    typing.Literal["UPLOAD", "URL", "RECORD", "TTS", "EXTRACT", "PLATFORM_IMPORT"], typing.Any
]
