# This file was auto-generated by Fern from our API Definition.

from ...core.unchecked_base_model import UncheckedBaseModel
import typing
import pydantic
import typing_extensions
from ...core.serialization import FieldMetadata
from ...core.pydantic_utilities import IS_PYDANTIC_V2


class Audio(UncheckedBaseModel):
    """
    Recorded/Captured audio input
    """

    type: typing.Literal["audio"] = "audio"
    url: str = pydantic.Field()
    """
    URL of the audio to be used for generation
    """

    ref_id: typing_extensions.Annotated[typing.Optional[str], FieldMetadata(alias="refId")] = pydantic.Field(
        default=None
    )
    """
    Reference identifier for this audio input, used to link audio inputs to specific segments when using [segments](/api-reference/api/generate-api/create#request.body.segments). Required when using segments array.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
