# This file was auto-generated by Fern from our API Definition.

from ...core.unchecked_base_model import UncheckedBaseModel
from .model import Model
import pydantic
import typing
from .input import Input
from .generation_options import GenerationOptions
from .generation_segment import GenerationSegment
import typing_extensions
from ...core.serialization import FieldMetadata
from ...core.pydantic_utilities import IS_PYDANTIC_V2


class CreateGenerationDto(UncheckedBaseModel):
    model: Model = pydantic.Field()
    """
    name of the model to use for generation.
    """

    input: typing.List[Input] = pydantic.Field()
    """
    Array of input objects. Must include one video input item and at least one audio input item. Audio input items can be provided as either: recorded/captured audio url or a text-to-speech input with tts provider configuration. When using segments, multiple audio inputs can be provided with unique refId values.
    """

    options: typing.Optional[GenerationOptions] = pydantic.Field(default=None)
    """
    additional options available for generation.
    """

    segments: typing.Optional[typing.List[GenerationSegment]] = pydantic.Field(default=None)
    """
    segments definition list. When provided, allows defining one or more video segments with different audio inputs for each segment. Each segment specifies a time range and references an audio input by refId.
    """

    webhook_url: typing_extensions.Annotated[typing.Optional[str], FieldMetadata(alias="webhookUrl")] = pydantic.Field(
        default=None
    )
    """
    webhook url for generation status updates. once the generation completes we will send a POST request to the webhook url with the generation data.
    """

    output_file_name: typing_extensions.Annotated[typing.Optional[str], FieldMetadata(alias="outputFileName")] = (
        pydantic.Field(default=None)
    )
    """
    Base filename for the generated output without extension. The .mp4 extension will be added automatically.  Only alphanumeric characters, underscores, and hyphens are allowed, up to 255 characters.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
