# This file was auto-generated by Fern from our API Definition.

import typing
from .batch_response import BatchResponse
from .validation_response import ValidationResponse

CreateBatchResponse = typing.Union[BatchResponse, ValidationResponse]
