# This file was auto-generated by Fern from our API Definition.

from ...core.unchecked_base_model import UncheckedBaseModel
import typing
import typing_extensions
from ...core.serialization import FieldMetadata
import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2


class ElevenLabs(UncheckedBaseModel):
    name: typing.Literal["elevenlabs"] = "elevenlabs"
    voice_id: typing_extensions.Annotated[str, FieldMetadata(alias="voiceId")] = pydantic.Field()
    """
    sync voice id (copied from cloned voices in the Studio) or ElevenLabs voice ID. Required.
    """

    script: str = pydantic.Field()
    """
    script to be used for generation
    """

    stability: typing.Optional[float] = pydantic.Field(default=None)
    """
    determines how stable the voice is and the randomness between each generation. lower values introduce broader emotional range for the voice. higher values can result in a monotonous voice with limited emotion.
    """

    similarity_boost: typing_extensions.Annotated[typing.Optional[float], FieldMetadata(alias="similarityBoost")] = (
        pydantic.Field(default=None)
    )
    """
    determines how closely the ai should adhere to the original voice when attempting to replicate it.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
