# This file was auto-generated by Fern from our API Definition.

from ...core.unchecked_base_model import UncheckedBaseModel
import pydantic
from .segment_audio_input import SegmentAudioInput
from ...core.pydantic_utilities import IS_PYDANTIC_V2
import typing


class GenerationSegment(UncheckedBaseModel):
    """
    Defines a video segment with its corresponding audio input. Used for multi-segment lipsync generations where different audio tracks can be applied to different video segments.
    """

    start_time: float = pydantic.Field()
    """
    Segment start time in seconds
    """

    end_time: float = pydantic.Field()
    """
    Segment end time in seconds
    """

    audio_input: SegmentAudioInput = pydantic.Field()
    """
    Audio configuration for this segment
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
