# This file was auto-generated by Fern from our API Definition.

import typing

Model = typing.Union[
    typing.Literal["lipsync-2", "lipsync-1.9.0-beta", "lipsync-1.8.0", "lipsync-1.7.1", "lipsync-1.6.0"], typing.Any
]
