# This file was auto-generated by Fern from our API Definition.

from ...core.unchecked_base_model import UncheckedBaseModel
import pydantic
from .model_type import ModelType
import typing
import typing_extensions
import datetime as dt
from ...core.serialization import FieldMetadata
from ...core.pydantic_utilities import IS_PYDANTIC_V2


class ModelInfo(UncheckedBaseModel):
    """
    Information about an available Sync model.
    """

    id: str = pydantic.Field()
    """
    Unique model identifier.
    """

    name: str = pydantic.Field()
    """
    Model name (e.g., lipsync-2, react-1).
    """

    type: ModelType = pydantic.Field()
    """
    The type of model.
    """

    version: str = pydantic.Field()
    """
    Model version string.
    """

    description: typing.Optional[str] = pydantic.Field(default=None)
    """
    Model description.
    """

    deprecated_at: typing_extensions.Annotated[typing.Optional[dt.datetime], FieldMetadata(alias="deprecatedAt")] = (
        pydantic.Field(default=None)
    )
    """
    Deprecation timestamp. Models with this field set are excluded from the list endpoint response.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
