# This file was auto-generated by Fern from our API Definition.

from ...core.unchecked_base_model import UncheckedBaseModel
import typing
from .asset import Asset
import pydantic
import typing_extensions
from ...core.serialization import FieldMetadata
from ...core.pydantic_utilities import IS_PYDANTIC_V2


class PaginatedAssetsResponse(UncheckedBaseModel):
    """
    Paginated list of assets.
    """

    items: typing.List[Asset] = pydantic.Field()
    """
    Array of assets.
    """

    next_cursor: typing_extensions.Annotated[typing.Optional[str], FieldMetadata(alias="nextCursor")] = pydantic.Field(
        default=None
    )
    """
    Cursor for fetching the next page of results.
    """

    total_count: typing_extensions.Annotated[typing.Optional[int], FieldMetadata(alias="totalCount")] = pydantic.Field(
        default=None
    )
    """
    Total number of assets matching the query.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
