# This file was auto-generated by Fern from our API Definition.

from ...core.pydantic_utilities import UniversalBaseModel
from .tts_provider_config import TtsProviderConfig
import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2
import typing


class TextInput(UniversalBaseModel):
    """
    Text to speech input
    """

    provider: TtsProviderConfig = pydantic.Field()
    """
    Integration provider configuration
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
