# This file was auto-generated by Fern from our API Definition.

from ...core.unchecked_base_model import UncheckedBaseModel
import typing
import pydantic
from .segment_secs import SegmentSecs
from .segment_frames import SegmentFrames
from ...core.pydantic_utilities import IS_PYDANTIC_V2


class Video(UncheckedBaseModel):
    type: typing.Literal["video"] = "video"
    url: str = pydantic.Field()
    """
    URL of the video to be used for generation
    """

    segments_secs: typing.Optional[SegmentSecs] = pydantic.Field(default=None)
    """
    [DEPRECATED] Use the top-level [segments](/api-reference/api/generate-api/create#request.body.segments) array instead for multi-segment support.
    """

    segments_frames: typing.Optional[SegmentFrames] = pydantic.Field(default=None)
    """
    [DEPRECATED] Use the top-level [segments](/api-reference/api/generate-api/create#request.body.segments) array instead for multi-segment support. frames 100 and 200 of the video
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
