# This file was auto-generated by Fern from our API Definition.

from ...core.api_error import ApiError
from ..types.generation_error import GenerationError


class BadRequestError(ApiError):
    def __init__(self, body: GenerationError):
        super().__init__(status_code=400, body=body)
