# This file was auto-generated by Fern from our API Definition.

from ..core.client_wrapper import SyncClientWrapper
from .raw_client import RawAssetsClient
import typing
from ..common.types.asset_sort import AssetSort
from ..common.types.asset_type import AssetType
from ..core.request_options import RequestOptions
from ..common.types.paginated_assets_response import PaginatedAssetsResponse
from ..common.types.asset_id import AssetId
from ..common.types.asset import Asset
from ..core.client_wrapper import AsyncClientWrapper
from .raw_client import AsyncRawAssetsClient


class AssetsClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawAssetsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawAssetsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawAssetsClient
        """
        return self._raw_client

    def list(
        self,
        *,
        project_id: typing.Optional[str] = None,
        limit: typing.Optional[int] = None,
        cursor: typing.Optional[str] = None,
        search_query: typing.Optional[str] = None,
        sort_by: typing.Optional[AssetSort] = None,
        types: typing.Optional[typing.Sequence[AssetType]] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> PaginatedAssetsResponse:
        """
        List all assets in your organization's media library.

        Parameters
        ----------
        project_id : typing.Optional[str]
            Filter assets by project ID.

        limit : typing.Optional[int]
            Maximum number of assets to return (1-100).

        cursor : typing.Optional[str]
            Cursor for pagination.

        search_query : typing.Optional[str]
            Search assets by name.

        sort_by : typing.Optional[AssetSort]
            Sort order for the results.

        types : typing.Optional[typing.Sequence[AssetType]]
            Filter by asset types. Accepts multiple types as a comma-separated list (AUDIO, VIDEO, IMAGE).

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PaginatedAssetsResponse
            Assets retrieved successfully

        Examples
        --------
        from sync import Sync

        client = Sync(
            api_key="YOUR_API_KEY",
        )
        client.assets.list(
            limit=10,
            sort_by="dateDesc",
        )
        """
        response = self._raw_client.list(
            project_id=project_id,
            limit=limit,
            cursor=cursor,
            search_query=search_query,
            sort_by=sort_by,
            types=types,
            request_options=request_options,
        )
        return response.data

    def get(self, id: AssetId, *, request_options: typing.Optional[RequestOptions] = None) -> Asset:
        """
        Retrieve a specific asset by ID.

        Parameters
        ----------
        id : AssetId

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        Asset
            Asset retrieved successfully

        Examples
        --------
        from sync import Sync

        client = Sync(
            api_key="YOUR_API_KEY",
        )
        client.assets.get(
            id="550e8400-e29b-41d4-a716-446655440000",
        )
        """
        response = self._raw_client.get(id, request_options=request_options)
        return response.data


class AsyncAssetsClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawAssetsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawAssetsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawAssetsClient
        """
        return self._raw_client

    async def list(
        self,
        *,
        project_id: typing.Optional[str] = None,
        limit: typing.Optional[int] = None,
        cursor: typing.Optional[str] = None,
        search_query: typing.Optional[str] = None,
        sort_by: typing.Optional[AssetSort] = None,
        types: typing.Optional[typing.Sequence[AssetType]] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> PaginatedAssetsResponse:
        """
        List all assets in your organization's media library.

        Parameters
        ----------
        project_id : typing.Optional[str]
            Filter assets by project ID.

        limit : typing.Optional[int]
            Maximum number of assets to return (1-100).

        cursor : typing.Optional[str]
            Cursor for pagination.

        search_query : typing.Optional[str]
            Search assets by name.

        sort_by : typing.Optional[AssetSort]
            Sort order for the results.

        types : typing.Optional[typing.Sequence[AssetType]]
            Filter by asset types. Accepts multiple types as a comma-separated list (AUDIO, VIDEO, IMAGE).

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PaginatedAssetsResponse
            Assets retrieved successfully

        Examples
        --------
        import asyncio

        from sync import AsyncSync

        client = AsyncSync(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.assets.list(
                limit=10,
                sort_by="dateDesc",
            )


        asyncio.run(main())
        """
        response = await self._raw_client.list(
            project_id=project_id,
            limit=limit,
            cursor=cursor,
            search_query=search_query,
            sort_by=sort_by,
            types=types,
            request_options=request_options,
        )
        return response.data

    async def get(self, id: AssetId, *, request_options: typing.Optional[RequestOptions] = None) -> Asset:
        """
        Retrieve a specific asset by ID.

        Parameters
        ----------
        id : AssetId

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        Asset
            Asset retrieved successfully

        Examples
        --------
        import asyncio

        from sync import AsyncSync

        client = AsyncSync(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.assets.get(
                id="550e8400-e29b-41d4-a716-446655440000",
            )


        asyncio.run(main())
        """
        response = await self._raw_client.get(id, request_options=request_options)
        return response.data
