# This file was auto-generated by Fern from our API Definition.

from ..core.client_wrapper import SyncClientWrapper
import typing
from ..common.types.asset_sort import AssetSort
from ..common.types.asset_type import AssetType
from ..core.request_options import RequestOptions
from ..core.http_response import HttpResponse
from ..common.types.paginated_assets_response import PaginatedAssetsResponse
from ..core.unchecked_base_model import construct_type
from ..common.errors.unauthorized_error import UnauthorizedError
from ..common.types.generation_error import GenerationError
from ..common.errors.internal_server_error import InternalServerError
from json.decoder import JSONDecodeError
from ..core.api_error import ApiError
from ..common.types.asset_id import AssetId
from ..common.types.asset import Asset
from ..core.jsonable_encoder import jsonable_encoder
from ..common.errors.not_found_error import NotFoundError
from ..core.client_wrapper import AsyncClientWrapper
from ..core.http_response import AsyncHttpResponse


class RawAssetsClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._client_wrapper = client_wrapper

    def list(
        self,
        *,
        project_id: typing.Optional[str] = None,
        limit: typing.Optional[int] = None,
        cursor: typing.Optional[str] = None,
        search_query: typing.Optional[str] = None,
        sort_by: typing.Optional[AssetSort] = None,
        types: typing.Optional[typing.Sequence[AssetType]] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[PaginatedAssetsResponse]:
        """
        List all assets in your organization's media library.

        Parameters
        ----------
        project_id : typing.Optional[str]
            Filter assets by project ID.

        limit : typing.Optional[int]
            Maximum number of assets to return (1-100).

        cursor : typing.Optional[str]
            Cursor for pagination.

        search_query : typing.Optional[str]
            Search assets by name.

        sort_by : typing.Optional[AssetSort]
            Sort order for the results.

        types : typing.Optional[typing.Sequence[AssetType]]
            Filter by asset types. Accepts multiple types as a comma-separated list (AUDIO, VIDEO, IMAGE).

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[PaginatedAssetsResponse]
            Assets retrieved successfully
        """
        _response = self._client_wrapper.httpx_client.request(
            "v2/assets",
            method="GET",
            params={
                "projectId": project_id,
                "limit": limit,
                "cursor": cursor,
                "searchQuery": search_query,
                "sortBy": sort_by,
                "types": types,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    PaginatedAssetsResponse,
                    construct_type(
                        type_=PaginatedAssetsResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 401:
                raise UnauthorizedError(
                    typing.cast(
                        GenerationError,
                        construct_type(
                            type_=GenerationError,  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            if _response.status_code == 500:
                raise InternalServerError(
                    typing.cast(
                        GenerationError,
                        construct_type(
                            type_=GenerationError,  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, body=_response.text)
        raise ApiError(status_code=_response.status_code, body=_response_json)

    def get(self, id: AssetId, *, request_options: typing.Optional[RequestOptions] = None) -> HttpResponse[Asset]:
        """
        Retrieve a specific asset by ID.

        Parameters
        ----------
        id : AssetId

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[Asset]
            Asset retrieved successfully
        """
        _response = self._client_wrapper.httpx_client.request(
            f"v2/assets/{jsonable_encoder(id)}",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    Asset,
                    construct_type(
                        type_=Asset,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 401:
                raise UnauthorizedError(
                    typing.cast(
                        GenerationError,
                        construct_type(
                            type_=GenerationError,  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    typing.cast(
                        GenerationError,
                        construct_type(
                            type_=GenerationError,  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            if _response.status_code == 500:
                raise InternalServerError(
                    typing.cast(
                        GenerationError,
                        construct_type(
                            type_=GenerationError,  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, body=_response.text)
        raise ApiError(status_code=_response.status_code, body=_response_json)


class AsyncRawAssetsClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._client_wrapper = client_wrapper

    async def list(
        self,
        *,
        project_id: typing.Optional[str] = None,
        limit: typing.Optional[int] = None,
        cursor: typing.Optional[str] = None,
        search_query: typing.Optional[str] = None,
        sort_by: typing.Optional[AssetSort] = None,
        types: typing.Optional[typing.Sequence[AssetType]] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[PaginatedAssetsResponse]:
        """
        List all assets in your organization's media library.

        Parameters
        ----------
        project_id : typing.Optional[str]
            Filter assets by project ID.

        limit : typing.Optional[int]
            Maximum number of assets to return (1-100).

        cursor : typing.Optional[str]
            Cursor for pagination.

        search_query : typing.Optional[str]
            Search assets by name.

        sort_by : typing.Optional[AssetSort]
            Sort order for the results.

        types : typing.Optional[typing.Sequence[AssetType]]
            Filter by asset types. Accepts multiple types as a comma-separated list (AUDIO, VIDEO, IMAGE).

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[PaginatedAssetsResponse]
            Assets retrieved successfully
        """
        _response = await self._client_wrapper.httpx_client.request(
            "v2/assets",
            method="GET",
            params={
                "projectId": project_id,
                "limit": limit,
                "cursor": cursor,
                "searchQuery": search_query,
                "sortBy": sort_by,
                "types": types,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    PaginatedAssetsResponse,
                    construct_type(
                        type_=PaginatedAssetsResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 401:
                raise UnauthorizedError(
                    typing.cast(
                        GenerationError,
                        construct_type(
                            type_=GenerationError,  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            if _response.status_code == 500:
                raise InternalServerError(
                    typing.cast(
                        GenerationError,
                        construct_type(
                            type_=GenerationError,  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, body=_response.text)
        raise ApiError(status_code=_response.status_code, body=_response_json)

    async def get(
        self, id: AssetId, *, request_options: typing.Optional[RequestOptions] = None
    ) -> AsyncHttpResponse[Asset]:
        """
        Retrieve a specific asset by ID.

        Parameters
        ----------
        id : AssetId

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[Asset]
            Asset retrieved successfully
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"v2/assets/{jsonable_encoder(id)}",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    Asset,
                    construct_type(
                        type_=Asset,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 401:
                raise UnauthorizedError(
                    typing.cast(
                        GenerationError,
                        construct_type(
                            type_=GenerationError,  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    typing.cast(
                        GenerationError,
                        construct_type(
                            type_=GenerationError,  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            if _response.status_code == 500:
                raise InternalServerError(
                    typing.cast(
                        GenerationError,
                        construct_type(
                            type_=GenerationError,  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, body=_response.text)
        raise ApiError(status_code=_response.status_code, body=_response_json)
