# This file was auto-generated by Fern from our API Definition.

from ..core.pydantic_utilities import UniversalBaseModel
from .create_generation_dto_model import CreateGenerationDtoModel
import pydantic
import typing
from .create_generation_dto_input_item import CreateGenerationDtoInputItem
from .generation_options import GenerationOptions
import typing_extensions
from ..core.serialization import FieldMetadata
from ..core.pydantic_utilities import IS_PYDANTIC_V2


class CreateGenerationDto(UniversalBaseModel):
    model: CreateGenerationDtoModel = pydantic.Field()
    """
    name of the model to use for generation.
    """

    input: typing.List[CreateGenerationDtoInputItem] = pydantic.Field()
    """
    Array of input objects. Must include one video input and either an audio or text input.
    """

    options: typing.Optional[GenerationOptions] = pydantic.Field(default=None)
    """
    additional options available for generation.
    """

    webhook_url: typing_extensions.Annotated[typing.Optional[str], FieldMetadata(alias="webhookUrl")] = pydantic.Field(
        default=None
    )
    """
    webhook url for generation status updates. once the generation completes we will send a POST request to the webhook url with the generation data.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
