# This file was auto-generated by Fern from our API Definition.

from ..core.pydantic_utilities import UniversalBaseModel
import typing
import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2


class VideoInputItem(UniversalBaseModel):
    url: str
    segments_secs: typing.Optional[typing.List[typing.List[float]]] = pydantic.Field(default=None)
    """
    Start and end time in seconds for each video segment to apply generation to
    """

    segments_frames: typing.Optional[typing.List[typing.List[float]]] = pydantic.Field(default=None)
    """
    Start and end frames for each video segment to apply generation to
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
